DROP TABLE messages CASCADE;
DROP TABLE channels CASCADE;
DROP TABLE users_guilds CASCADE;
DROP TABLE guilds CASCADE;
DROP TABLE sessions CASCADE;
DROP TABLE users CASCADE;
DROP TABLE user_uploads CASCADE;
DROP COLLATION case_insensitive CASCADE;
